import {
  AppWindow,
  BookOpen,
  Calculator,
  CalendarDays,
  Camera,
  Clock3,
  CloudSun,
  Contact,
  Container,
  Folder,
  Gauge,
  Globe,
  Grid2x2,
  HandHelping,
  HardDrive,
  Image,
  LayoutGrid,
  Map,
  Music,
  NotebookPen,
  Palette,
  Settings,
  Sheet,
  SquareTerminal,
  StickyNote,
  Video,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { AppId } from "./apps";

export const APP_ICONS: Record<AppId, LucideIcon> = {
  welcome: HandHelping,
  terminal: SquareTerminal,
  files: Folder,
  editor: AppWindow,
  browser: Globe,
  monitor: Gauge,
  calc: Calculator,
  settings: Settings,
  software: Grid2x2,
  notes: StickyNote,
  writer: NotebookPen,
  sheets: Sheet,
  calendar: CalendarDays,
  clock: Clock3,
  weather: CloudSun,
  maps: Map,
  photos: Image,
  paint: Palette,
  music: Music,
  videos: Video,
  help: BookOpen,
  disk: HardDrive,
  contacts: Contact,
  screenshot: Camera,
  containers: Container,
};

export const LAUNCHER_ICON = LayoutGrid;
